### PR TITLE
Changed deps from 4.4.1<=ffmpeg to  4.4.1<=ffmpeg<6

### PR DESCRIPTION
**Pull request by mattaw**
Until ffmpeg 6 support in screentogif change dependency from 4.4.1<=ffmpeg to  4.4.1<=ffmpeg<6

Thank you so much for this project and maintaining it, it is so powerful as a teaching aid.

### CODE REVIEW

**Comment by mattaw** [comment]
In case version 2.38.1 is not OK I split the commits between fixing the ffmpeg deps and updating the version.

**Comment by mattaw** [comment]
Awesome news to see on reddit you are working on v3!

In the meantime could you merge and push my PR to Chocolatey, as ScreenToGif from there is a couple of releases in the past and it is pulling in FFMPEG 6 from Chocolatey which doesn't work.

**Comment by mattaw** [comment]
Could you push to chocolatey by any chance? I had to setup a new pc recently and I still get version 2.37 and ffmpeg 6.

**Comment by NickeManarin** [comment]
Done, waiting for approval.

**Comment by mattaw** [comment]
Thanks for all your hard work - seriously. I don't want to give the
impression I am ungrateful!

**Pull request merged**
